# -*- encoding: utf-8 -*-

MAX_PAIRS = 32767

EVENT_ESC = "ESC"
EVENT_RESIZE = "RESIZE"
EVENT_ENTER = "ENTER"
EVENT_BACKSPACE = "BACKSPACE"
EVENT_UP = "UP"
EVENT_DOWN = "DOWN"
EVENT_LEFT = "LEFT"
EVENT_RIGHT = "RIGHT"
EVENT_CTRL_C = "CTRL+C"
EVENT_UNHANDLED = "???"
